# Alacritty configuration file definition - https://alacritty.org/config-alacritty.html

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0
blur = false
decorations = "Full"
startup_mode = "Fullscreen"
option_as_alt = "Both"

[cursor]
style.shape = "Block"
style.blinking = "Never"
unfocused_hollow = true

[font]
size = 18
normal.family = "Hack Nerd Font Mono"
# normal.family = "GohuFont 14 Nerd Font Mono"
normal.style = "Regular"

