# Alacritty configuration file definition - https://alacritty.org/config-alacritty.html

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
blur = true
startup_mode = "Fullscreen"
option_as_alt = "Both"

[font]
size = 18

[font.normal]
family = "Hack Nerd Font Mono"
# family = "GohuFont 14 Nerd Font Mono"
style = "Regular"


