# Alacritty configuration file definition - https://alacritty.org/config-alacritty.html
import = [
	"~/.config/alacritty/overrides.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
blur = false
decorations = "Full"
option_as_alt = "Both"

[cursor]
style.shape = "Block"
style.blinking = "Never"
unfocused_hollow = true

[keyboard]
bindings = [
	{ key = "F12", action = "ToggleMaximized" },
	{ key = "+", mods = "Control", action = "IncreaseFontSize" },
	{ key = "-", mods = "Control", action = "DecreaseFontSize" },
]

[colors]
primary.background = "#282a36"
transparent_background_colors = true

[selection]
save_to_clipboard = false

[font]
size = 18
normal.family = "Hack Nerd Font Mono"
# normal.family = "GohuFont 14 Nerd Font Mono"
normal.style = "Regular"
